# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SITE CONFIGURATION
url: "https://thecodecat.it" # the base hostname & protocol for your site, e.g. http://example.com

# THEME-SPECIFIC CONFIGURATION
title: TheCodeCat
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to TheCodeCat, where passion for technology, programming, and art intertwine to create a truly unique and immersive blog experience.
  As your guide, I explore the dynamic realms of .NET, C#, Azure, AI, and generative art, sharing my insights, experiences, and knowledge to inspire and inform.
  Join me on this exhilarating journey and stay ahead of the curve with thought-provoking articles, in-depth tutorials, and the latest tech news.
avatar: assets/img/avatar.png
favicon: assets/favicon.ico

# USER INFO
email: thecodecat23@gmail.com
twitter_username: thecodecat23
github_username:  thecodecat23

# Footer and Header's text
header_text: Don't pro-cat-stinate, follow TheCodeCat today and start feline good about programming!
footer_text: Copyright @TheCodeCat 2023

# Header's image
header_feature_image: assets/img/header/thecodecat-header.png
header_feature_image_responsive: true

# Blog
post_navigation: true
excerpt: true

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
color_theme: auto # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/