# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TheCodeCat Blog
email: thecodecat23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to TheCodeCat, where passion for technology, programming, and art intertwine to create a truly unique and immersive blog experience.
  As your guide, I explore the dynamic realms of .NET, C#, Azure, AI, and generative art, sharing my insights, experiences, and knowledge to inspire and inform.
  Join me on this exhilarating journey and stay ahead of the curve with thought-provoking articles, in-depth tutorials, and the latest tech news.
baseurl: "/thecodecat-blog" # the subpath of your site, e.g. /blog
url: "https://thecodecat23.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thecodecat23
github_username:  thecodecat23
color_theme: auto

# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"

# Footer and Header's text
header_text: Unravel the Catventures of a Feline-Enthusiast Developer in the Tech World
footer_text: Copyright 2017

Header's image
header_feature_image: assets/img/header/thecodecat_header.jpg
header_feature_image_responsive: true

# Build settings
theme: type-on-strap
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/